### ISSUE TITLE
[front] [admin] [back] Viewpoint creation

### ISSUE THREAD

**Issue by submarcos** [Terralego/terra-opp#24]
some lists are populated with keys in viewpoints properties
so, to access the lists in frontend filters, we need to be able to set these properties 

* Firstly, we need to be able to define these in viewpoint creation / update form

* Secondly, we need to separate themes and cities to specific models

**Comment by AL9000** [comment]
@submarcos For the second point, you which to have a separate model for themes and coties and also have a specific endpoint?

Right now, all those details are given on this endpoint: /api/viewpoints/filters/

**Comment by submarcos** [comment]
* as discussed with @jrmi 

1. list given by /api/viewpoints/filters/ are populated from viewpoint properties
2. Terra-admin should provide way to set new city or theme, and not be limit by existing list (-> circular problem : no viewpoint / no value because admin deals with SELECT instead of input text) -> should be fixed in admin with autocomplete and free text field
3. In the future, separate to specific models because it let possibility to define fixed list (list can exists without viewpoints, and list should not be managed just by viewpoint properties at creation, in some project list should be fixed, and managed in custom admin menu.

For the last part, it's not a problem to keep api/viewpoint/filters, if values are coming for model's list and not from viewpoint properties list

**Comment by submarcos** [comment]
link with https://github.com/Terralego/terra-admin/issues/263
