### ISSUE TITLE
[back] Don't force S3 storage

### ISSUE THREAD

**Issue by submarcos** [Terralego/terra-opp#25]
S3 is a good idea for production environment, but we should use it only if there it's available in public.
But we should not force project to use it.
It's the project settings which should define default storage to use.
We need to adapt some helper code, for a wrong problem with url access in pdf template by weasyprint.
With S3, media url are absolute. With filesystem storage, they are relative, but it's possible to user request.build_absolute_uri and pass it to weasyprint
And define default dev mode without s3 storage

**Comment by submarcos** [comment]
- [ ] pass request.build.absolute_uri to weasyprint.base_url
- [ ] don't use minio or other storage in local development
- [ ] in production, s3 storage generate full public accessible url for media files

**Comment by AL9000** [comment]
See https://github.com/Terralego/opp-back/pull/24
